AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  parola-inference-pipeline
  
  SAM Template for the Parola Project Pelagic Model inference pipeline with StarISDAWorkflow cloud features.

Resources:
  ParolaInferenceFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Architectures:
        - x86_64
      MemorySize: 3008
      Timeout: 900
      FunctionUrlConfig:
        AuthType: NONE
      Environment:
        Variables:
          MODEL_BUCKET_NAME: !Ref ParolaDataBucket
          COPERNICUS_USERNAME: "sstu"
          COPERNICUS_PASSWORD: "StarISDA!234"
          DATABASE_URL: "postgresql://postgres.aafqdvhfycqbsvmvaxmz:StarISDA!23@aws-1-ap-southeast-2.pooler.supabase.com:6543/postgres?pgbouncer=true"
          OPEN_METEO_MARINE_API_URL: "https://marine-api.open-meteo.com/v1/marine"
          OPEN_METEO_FORECAST_API_URL: "https://api.open-meteo.com/v1/forecast"
          PAGASA_BULLETIN_API_URL: "https://pagasa.chlod.net/api/v1/bulletin/list"
          SAFETY_WIND_THRESHOLD_KNOTS: "20.0"
          SAFETY_WAVE_THRESHOLD_METERS: "3.0"
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref ParolaDataBucket
        - S3WritePolicy:
            BucketName: !Ref ParolaDataBucket
      Events:
        SixHourInferenceSchedule:
          Type: Schedule
          Properties:
            Schedule: 'rate(6 hours)'
            Name: ParolaSixHourInferenceSchedule
            Description: Automatically trigger model inference & weather workflow every 6 hours
        ApiTrigger:
          Type: Api
          Properties:
            Path: /update-workflow
            Method: POST
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: .
      DockerTag: latest

  ParolaDataBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "parola-data-bucket-${AWS::AccountId}-${AWS::Region}"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

Outputs:
  ParolaInferenceFunctionArn:
    Description: "Parola Inference Lambda Function ARN"
    Value: !GetAtt ParolaInferenceFunction.Arn
  ParolaInferenceFunctionUrl:
    Description: "Function URL to trigger workflow on demand via HTTP"
    Value: !GetAtt ParolaInferenceFunctionUrl.FunctionUrl
  ParolaDataBucketName:
    Description: "S3 Bucket containing the model and output advisories"
    Value: !Ref ParolaDataBucket
